[workspace]
channels = ["conda-forge"]
name = "PopPUNK-mod"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.6,<3"
pandas = ">=3.0.3,<4"
matplotlib = ">=3.10.9,<4"
tqdm = ">=4.67.3,<5"
scipy = ">=1.17.1,<2"
r-optparse = ">=1.8.2,<2"
