import pickle
import os
import numpy as np
import pandas as pd
import argparse
from extract_poppunk_distances import listDistInts, isolateNameToLabel
from collections import defaultdict
from tqdm import tqdm
from scipy.stats import norm, false_discovery_control

# command line parsing
def get_options():

    parser = argparse.ArgumentParser(description='Determine odds ratios of genes being found in lower (Lo) or higher (Hi) distance comparisons', prog='python gene_odds_ratio.py')

    # input options
    parser.add_argument('--distances', help='Path to .dists prefix generated by PopPUNK (required)',
                                    required=True)
    parser.add_argument('--pa-matrix', help='Path to pa matrix. Sample names must match those in distances file (required)',
                                    required=True)
    parser.add_argument('--quantiles', help='Comma separated list of two quantiles to compare. Default = 0.25,0.75',
                                    default="0.25,0.75")
    parser.add_argument('--distance-type', help='Which distance to use for quantiles. Options are "core", "accessory" or "both". Default = "core"',
                                    choices=["core", "accessory", "both"],
                                    default="core")
    parser.add_argument('--n-samples', help='Number of distances to sample per gene per quantile. Default = 1000',
                                    type=int,
                                    default=1000)
    parser.add_argument('--outpref', help='Output prefix (required)',
                                    required = True)
    return parser.parse_args()

def main():
    args = get_options()


    # open stored distances
    with open(args.distances + ".pkl", 'rb') as pickle_file:
        rlist, qlist, self = pickle.load(pickle_file)

    # get names order
    r_names = isolateNameToLabel(rlist)
    q_names = isolateNameToLabel(qlist)

    # read in distance matrix
    X = np.load(args.distances + ".npy")
    num_rows, num_cols = X.shape

    # if using both distances, calculate combined distance as sqrt(core^2 + accessory^2)
    if args.distance_type == "both":
        X[:,2] = np.sqrt(X[:,0]**2 + X[:,1]**2)

    # determine quantile distances
    if args.distance_type == "core":
        dist_col = 0
    elif args.distance_type == "accessory":
        dist_col = 1
    elif args.distance_type == "both":
        dist_col = 2
    
    quantiles = sorted([float(q) for q in args.quantiles.split(",")])[:2] # take only first two quantiles if more are provided
    quantile_values = np.quantile(X[:,dist_col], quantiles)

    print("Quantiles: ", quantiles)
    print("Quantile values: ", quantile_values)

    # store reference distances
    ref_distances = defaultdict(lambda: {q: [] for q in quantiles})

    # for each genome, get number of genomes within margin of each quantile distance, where margin is the distance between the two quantiles
    print("Extracting subset of distances for each genome...")
    for i, (r_index, q_index) in enumerate(listDistInts(r_names, q_names, r_names == q_names)):
        ref, query, distance = q_names[q_index], r_names[r_index], X[i, dist_col]

        # avoid computing for completed references
        if all(len(ref_distances[ref][q]) >= args.n_samples for q in quantiles):
            continue

        for q_idx, q, q_value in zip(range(len(quantiles)), quantiles, quantile_values):
            if len(ref_distances[ref][q]) < args.n_samples:
                if (q_idx == 0 and distance <= q_value) or (q_idx == 1 and distance >= q_value):
                    ref_distances[ref][q].append((query, distance))
    
    del X # free memory

    # determine number of genes
    with open(args.pa_matrix, 'r') as pa_file:
        num_genes = sum(1 for line in pa_file) - 1 # subtract header

    progress_bar = tqdm(total=num_genes, desc="Calculating odds ratios", unit="gene")

    gene_odds_ratios = {}
    missing_genomes = set()
    with open(args.pa_matrix, 'r') as pa_file:
        genome_ids = pa_file.readline().rstrip().split(",")[1:] # first column is gene name
        # strip file extension from genome ids if present
        genome_ids = [os.path.splitext(gid)[0] for gid in genome_ids]

        # Build O(1) lookup dict to replace repeated O(n) list.index() calls
        genome_id_to_index = {gid: i for i, gid in enumerate(genome_ids)}

        # Pre-convert ref_distances to numpy index arrays once, amortised over all genes
        ref_distances_idx = {}
        for genome, q_dict in ref_distances.items():
            ref_distances_idx[genome] = {}
            for q, pairs in q_dict.items():
                indices = []
                for query, _ in pairs:
                    if query not in genome_id_to_index:
                        raise ValueError(f"Query genome {query} from distance matrix not found in pa matrix")
                    indices.append(genome_id_to_index[query])
                ref_distances_idx[genome][q] = np.array(indices, dtype=np.intp)

        for line in pa_file:
            gene, *presence = line.rstrip().split(",")
            presence = np.array(presence).astype(int)
            
            # find isolates with gene present
            gene_presence = presence.astype(bool)

            # get list of indices with gene present
            gene_present_indices = np.where(gene_presence)[0]
            genomes_gene_present = [genome_ids[i] for i in gene_present_indices]

            concordant_low, concordant_high, discordant_low, discordant_high = 0.5, 0.5, 0.5, 0.5 # pseudocounts to avoid division by zero

            # track if any entries found for gene
            gene_updated = False

            for genome in genomes_gene_present:
                if genome not in ref_distances_idx:
                    missing_genomes.add(genome) 
                    continue # skip genomes with no distance data
                for q_idx, q in enumerate(quantiles):
                    query_indices = ref_distances_idx[genome][q]
                    if len(query_indices) > 0:
                        has_gene = gene_presence[query_indices]
                        count_with = int(has_gene.sum())
                        count_without = len(query_indices) - count_with

                        if count_with + count_without == 0:
                            continue # skip if no queries for this genome and quantile
                        else:
                            gene_updated = True
                        
                        if q_idx == 0:
                            concordant_low += count_with
                            discordant_low += count_without
                        else:
                            concordant_high += count_with
                            discordant_high += count_without

            if not gene_updated:
                odds_ratio, stderr, conf_interval_95, p_value = 1.0, 0.0, (1.0, 1.0), 1.0 # if no data for gene, set odds ratio to 1 with zero stderr and CI of (1,1)
            else:
                odds_ratio = (concordant_low / discordant_low) / (concordant_high / discordant_high)
                stderr = np.sqrt(1/concordant_low + 1/discordant_low + 1/concordant_high + 1/discordant_high)
                conf_interval_95 = (np.exp(np.log(odds_ratio) - 1.96*stderr), np.exp(np.log(odds_ratio) + 1.96*stderr))
                z = np.log(odds_ratio) / stderr
                p_value = 2 * norm.sf(abs(z))

            gene_odds_ratios[gene] = (odds_ratio, stderr, conf_interval_95, p_value, concordant_low, discordant_low, concordant_high, discordant_high)
            progress_bar.update(1)

    progress_bar.close()

    # adjust p-values for multiple testing using Benjamini-Hochberg procedure
    p_values = [gene_odds_ratios[gene][3] for gene in gene_odds_ratios]
    p_adjusted = false_discovery_control(p_values)
    for i, gene in enumerate(gene_odds_ratios):
        odds_ratio, stderr, conf_interval_95, _, concordant_low, discordant_low, concordant_high, discordant_high = gene_odds_ratios[gene]
        gene_odds_ratios[gene] = (odds_ratio, stderr, conf_interval_95, p_adjusted[i], concordant_low, discordant_low, concordant_high, discordant_high)

    # calculate odds ratio for each gene and quantile
    print("Writing odds ratios to output file...")
    with open(args.outpref + "_odds_ratios.tsv", 'w') as oFile:
        oFile.write("Gene\tOdds_Ratio\tStdErr\tLower_CI\tUpper_CI\tP_Value\tSignificance\tConcordant_Low\tDiscordant_Low\tConcordant_High\tDiscordant_High\n")
        for gene in gene_odds_ratios:
            odds_ratio, stderr, conf_interval_95, p_value, concordant_low, discordant_low, concordant_high, discordant_high = gene_odds_ratios[gene]
            if (conf_interval_95[0] <= 1 <= conf_interval_95[1]) or p_value >= 0.05:
                significance = "NS"
            else:
                if conf_interval_95[0] > 1 and p_value < 0.05:
                    significance = "Lo"
                elif conf_interval_95[1] < 1 and p_value < 0.05:
                    significance = "Hi"
                else:
                    significance = "NS"
            oFile.write(f"{gene}\t{odds_ratio}\t{stderr}\t{conf_interval_95[0]}\t{conf_interval_95[1]}\t{p_value}\t{significance}\t{concordant_low}\t{discordant_low}\t{concordant_high}\t{discordant_high}\n")
    
    with open(args.outpref + "_missing_genomes.txt", 'w') as mFile:
        mFile.write("Genomes missing from distance data:\n")
        for genome in sorted(missing_genomes):
            mFile.write(f"{genome}\n")

if __name__ == "__main__":
    main()